Convert code from `queryselector` to product `array`
Disha-56843/point-of-sale pull request #5
Opened 2024-09-18 14:06 UTC by Disha-56843

- product data was get by queryselector which will now get from product array

2024-09-18 23:28 UTC, utsavsomaiya requested changes
Okay after this changes all should working as expected. Right?

2024-09-18 23:28 UTC, utsavsomaiya commented on script.js
> +                    // const productName2 = productElement2.querySelector('.item-name').innerText.toLowerCase()
I dont love comment!

Please remove it! Before pushing the code as we discussed you need to review first and then hit me to review!

2024-09-19 04:53 UTC, Disha-56843 commented
> Okay after this changes all should working as expected. Right?

no I'm still working on it

2024-09-19 04:55 UTC, Disha-56843 commented on script.js
> +                    // const productName2 = productElement2.querySelector('.item-name').innerText.toLowerCase()
> I dont love comment!
> 
> Please remove it! Before pushing the code as we discussed you need to review first and then hit me to review!

I want that code for future reference as I'm still working on it

2024-09-19 04:55 UTC, utsavsomaiya commented
<img width="498" alt="image" src="https://github.com/user-attachments/assets/caefdc33-49de-4a2a-bed7-5cacf42adec4">

Nothing in git ignore?

2024-09-19 04:56 UTC, utsavsomaiya commented on script.js
> +                    // const productName2 = productElement2.querySelector('.item-name').innerText.toLowerCase()
Yeah but you send me requested review so!

2024-09-19 05:01 UTC, Disha-56843 commented
> <img alt="image" width="498" src="https://private-user-images.githubusercontent.com/96036522/368846181-caefdc33-49de-4a2a-bed7-5cacf42adec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MjIwMjIsIm5iZiI6MTcyNjcyMTcyMiwicGF0aCI6Ii85NjAzNjUyMi8zNjg4NDYxODEtY2FlZmRjMzMtNDlkZS00YTJhLWJlZDctNWNhY2Y0MmFkZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA0NTUyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4YTgyNDhmODFiYTFmOGJkNGYyZmNlNmEzYzYyZDA0MzVjNDM1MjBhMDQ4Y2MzYmRkMjlmOGFlZTQ4ZDU2N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9u3hf3Ex47TWZ9-LUgBQYe6LFDLhrVB-m4qvjnPOYcw">
> 
> Nothing in git ignore?

yes i made that for vscode folder but now it is not required

2024-09-19 05:02 UTC, utsavsomaiya commented
Please delete it!

2024-09-20 08:50 UTC, merged